export const sortTypes = [
  { id: 1, query: "popularity.desc", name: "Popularite (descendante)" },
  { id: 2, query: "popularity.asc", name: "Popularité (ascendante)" },
  { id: 3, query: "title.desc", name: "Titre - Alphabétique (descendant)" },
  { id: 4, query: "title.asc", name: "Titre - Alphabétique (ascendant)" },
  { id: 5, query: "original_title.desc", name: "Titre (vo - descendant)" },
  { id: 6, query: "original_title.asc", name: "Titre (vo - ascendant)" },
  { id: 7, query: "revenue.desc", name: "Revenus (descendant)" },
  { id: 8, query: "revenue.asc", name: "Revenus (ascendant)" },
  { id: 9, query: "primary_release_date.desc", name: "Date de réalisation (descendante)" },
  { id: 10, query: "primary_release_date.asc", name: "Date de réalisation (ascendante)" },
  { id: 11, query: "vote_average.desc", name: "Note moyenne (descendante)" },
  { id: 12, query: "vote_average.asc", name: "Note moyenne (ascendante)" },
  { id: 13, query: "vote_count.desc", name: "Nombre de votants (descendante)" },
  { id: 14, query: "vote_count.asc", name: "Nombre de votants (ascendante)" },
];
